language: node_js
node_js: node

script:
    - npm run build

before_deploy:
    - touch ./build/.nojekyll

deploy:
    - provider: pages
      edge: true
      local_dir: build
      on:
          branch: master

    - provider: pages
      edge: true
      local_dir: build
      repo: lrc-maker/lrc-utils
      target-branch: master
      on:
          branch: master
          tags: true
